name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
    - name: setup node
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: '21.x'
    - name: install deps
      run: |
        # install app deps
        npm install
        # install build deps
        npm install -g @vercel/ncc
    - name: build
      run: |
        rm dist/index.js
        make
